{
 "title": "Network",
 "description": "Network latencies and availability",
 "tags": [ "networking" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Speedtest (Ping)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Ping" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth (Download)",
   "type": "stat",
   "description": "Download bandwidth",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speedtest TX/RX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Upload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth (uptime)",
   "type": "stat",
   "description": "Uptime bandwidth",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Upload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS AVG Query time",
   "type": "bargauge",
   "description": "DNS resolution average query time",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_domain",
     "groupBy": [
      { "params": [ "domain" ], "type": "tag" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ICMP Packet loss (%)",
   "type": "graph",
   "description": "Percentage of package lost ",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "Packet lost %" }
   ],
   "targets": [
    {
     "measurement": "ping",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP GET response time (ms)",
   "type": "graph",
   "description": "HTTP GET request response time (ms)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "GET" }
     ]
    }
   ]
  },
  {
   "title": "ICMP average response",
   "type": "graph",
   "description": "ICMP echo requests average latency.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "average (ms)" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping AVG response time (external)",
   "type": "gauge",
   "description": "Average response time for External Ping in ms.",
   "gridPos": { "h": 10, "w": 6, "x": 2, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "ping",
     "query": "SELECT \"average_response_ms\" FROM \"ping\" ",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "4.2.2.1" }
     ]
    }
   ]
  },
  {
   "title": "Interface: eth0 Tx/Rx",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Tx (Bytes)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "Rx (Bytes)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "Drop In",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "Drop Out",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "Ping Standard Deviation (ms)",
   "type": "heatmap",
   "description": "Standard Deviation (ms) heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "standard_deviation_ms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP response codes",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TraceRoute",
   "type": "gowee-traceroutemap-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(avg) as rtt, mean(loss) as loss from mtr WHERE now() - 5m < time group by hop, ip, host, dest\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}