---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: isp-checker
  labels:
    app: influxdb
    app.kubernetes.io/app: influxdb
    app.kubernetes.io/project: isp-checker
  name: influxdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: isp-checker
  labels:
    app: grafana
    app.kubernetes.io/app: grafana
    app.kubernetes.io/project: isp-checker
  name: grafana-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
