version: "3.3"
services:
  influxdb:
    labels:
      - "docker.group=ISP-Checker"
      - "docker.app=influxdb"
    container_name: influxdb
    image: influxdb:1.8.3-alpine
    expose:
      - 8086
    restart: on-failure
    volumes:
      - "influxdb-storage:/var/influxdb/data"
    env_file:
      - ../credentials.env
    ports:
      - 8086:8086
  telegraf:
    labels:
      - "docker.group=ISP-Checker"
      - "docker.app=telegraf"
    container_name: telegraf
    image: tty0/isp_telegraf:1.15.3
    volumes:
      - "../telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf"
    env_file:
      - ../credentials.env
    links:
      - "influxdb"
    depends_on:
      - "influxdb"
  grafana:
    labels:
      - "docker.group=ISP-Checker"
      - "docker.app=grafana"
    container_name: grafana
    image: grafana/grafana:7.2.1-ubuntu
    environment:
      - GF_INSTALL_PLUGINS=https://grafana.com/api/plugins/gowee-traceroutemap-panel/versions/0.2.3/download;gowee-traceroutemap-panel
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - "grafana-storage:/var/lib/grafana"
    links:
      - "influxdb"
    depends_on:
      - "influxdb"
      - "telegraf"
volumes:
  grafana-storage:
    external: true
  influxdb-storage:
    external: true
