{
 "title": "Network",
 "description": "Network latencies and availability",
 "tags": [
  "networking",
  "monitoring",
  "telegraf",
  "influxdb",
  "isp",
  "raspberry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "PingURL",
    "query": "SHOW TAG VALUES FROM \"ping\" WITH KEY = \"url\""
   },
   {
    "name": "NetInterface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE \"host\" =~ /$NetHost/"
   },
   {
    "name": "NetHost",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Speedtest (Ping)",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Ping" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth (Download)",
   "type": "stat",
   "description": "Download bandwidth",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1048576" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speedtest TX/RX",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Download" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Upload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bandwidth (Upload)",
   "type": "stat",
   "description": "Uptime bandwidth",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Upload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1048576" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ICMP average response",
   "type": "graph",
   "description": "ICMP echo requests average latency.",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "average (ms)" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$PingURL$/" }
     ]
    }
   ]
  },
  {
   "title": "Ping AVG response time",
   "type": "gauge",
   "description": "Average response time for External Ping in ms.",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "ping",
     "query": "SELECT \"average_response_ms\" FROM \"ping\" ",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$PingURL$/" }
     ]
    }
   ]
  },
  {
   "title": "DNS AVG Query time",
   "type": "bargauge",
   "description": "DNS resolution average query time",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_domain",
     "groupBy": [
      { "params": [ "domain" ], "type": "tag" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ICMP Packet loss (%)",
   "type": "graph",
   "description": "Percentage of package lost ",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "Packet lost %" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jitter (ICMP/HTTP)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "HTTP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$NetHost$/" }
     ]
    },
    {
     "alias": "ICMP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "standard_deviation_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$NetHost$/" }
     ]
    }
   ]
  },
  { "title": "Connectivity metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "$PingURL Ping",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "repeat": "PingURL",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"average_response_ms\") FROM \"ping\" WHERE (\"url\" =~ /^$PingURL$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP GET response time (ms)",
   "type": "graph",
   "description": "HTTP GET request response time (ms)",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "GET" }
     ]
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netstat",
     "query": "SELECT mean(\"tcp_close\") AS \"tcp_close\", mean(\"tcp_close_wait\") AS \"tcp_close_wait\", mean(\"tcp_closing\") AS \"tcp_colsing\", mean(\"tcp_fin_wait1\") AS \"tcp_fin_wait1\", mean(\"tcp_fin_wait2\") AS \"tcp_fin_wait2\", mean(\"tcp_last_ack\") AS \"tcp_last_ack\", mean(\"tcp_syn_recv\") AS \"tcp_syn_recv\", mean(\"tcp_syn_sent\") AS \"tcp_syn_sent\", mean(\"tcp_listen\") AS \"tcp_listen\", mean(\"tcp_time_wait\") AS \"tcp_time_wait\", mean(\"udp_socket\") AS \"udp_socket\", mean(\"tcp_established\") AS \"tcp_established\" FROM \"netstat\" WHERE (\"host\" =~ /^$NetHost$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "tcp_close" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tcp_close" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$NetHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface: $NetInterface (Tx/Rx)",
   "type": "graph",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Tx (Bytes)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$NetInterface$/" }
     ]
    },
    {
     "alias": "Rx (Bytes)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$NetInterface$/" }
     ]
    },
    {
     "alias": "Drop In",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$NetInterface$/" }
     ]
    },
    {
     "alias": "Drop Out",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$NetInterface$/" }
     ]
    },
    {
     "alias": "Error In",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$NetInterface$/" }
     ]
    },
    {
     "alias": "Error Out",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ "/1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$NetInterface$/" }
     ]
    }
   ]
  },
  {
   "title": "Ping Standard Deviation (ms)",
   "type": "heatmap",
   "description": "Standard Deviation (ms) heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "standard_deviation_ms" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$PingURL$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP response codes",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TraceRoute",
   "type": "gowee-traceroutemap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(avg) as rtt, mean(loss) as loss from mtr WHERE now() - 5m < time group by hop, ip, host, dest\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MiB Received ($NetInterface)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1048576" ], "type": "math" },
       { "params": [ "MiB Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$NetInterface$/" }
     ]
    }
   ]
  },
  {
   "title": "MiB Sent ($NetInterface)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1048576" ], "type": "math" },
       { "params": [ "MiB Sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=~", "value": "/^$NetInterface$/" }
     ]
    }
   ]
  },
  { "title": "Availability metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "$PingURL Ping",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 94 },
   "repeat": "PingURL",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100 - mean(\"percent_packet_loss\") FROM \"ping\" WHERE \"url\" =~ /^$PingURL$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}